on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-hello:
    name: Release Hello Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.21.0
          binary_name: "hello"
          compress_assets: off
          md5sum: false
          pre_command: "go install github.com/akavel/rsrc&&rsrc -ico ./build/logo.ico -o resources.syso&&go env -w CGO_ENABLED=1"
#          ldflags: "-extldflags -static -H windowsgui -s -w"

  releases-ts:
    name: Release Ts Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [windows, linux]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.21.0
          binary_name: "ts"
          project_path: "./ts"
          compress_assets: off
          md5sum: false